FROM python:3.12-slim-bullseye

WORKDIR /myapp

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/myapp
ENV ENV_FILE=.env.test

CMD ["pytest", "--cov=app", "--cov-report=html"]